speed-dreams/source-2.2.3/src/modules/graphic/ssggraph/grboard.cpp
speed-dreams/source-2.2.3/src/modules/graphic/ssggraph/grboard.h

Refactored existing methods very slightly and added documentation to most existing functions.
Documentation of how to update/add menu's and how to update the HUD can be found in the Drive under Guides > Updating the User Interface of Speed Dreams

V22F-72 Documentation of UI elements in speed dreams

---

speed-dreams/source-2.2.3/.gitignore
speed-dreams/source-2.2.3/src/modules/userinterface/legacymenu/mainscreens/ResearcherMenu.cpp
speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/frontend/InterventionConfig.cpp
speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/frontend/InterventionConfig.h

refactors code of the frontend so it complies with our code standards

Refactor frontend

---

speed-dreams/source-2.2.3/data/data/menu/ResearcherMenu.xml
speed-dreams/source-2.2.3/src/modules/userinterface/legacymenu/mainscreens/ResearcherMenu.cpp
speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backend/Mediator.h
speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backend/Mediator.inl
speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backend/SDAConfig.cpp
speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backend/SDAConfig.h
speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backendUnitTests/ConfigTests.cpp

V22F-131 Data anonymous

---

speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backend/Mediator.inl

Speed info sent to black box fixed to be the actual speed

V22F-344: drivesituation speed

---

speed-dreams/source-2.2.3/data/data/menu/DataSelectionMenu.xml
speed-dreams/source-2.2.3/data/data/menu/mainmenu.xml
speed-dreams/source-2.2.3/src/modules/sound/snddefault/OpenalSoundInterface.cpp
speed-dreams/source-2.2.3/src/modules/userinterface/legacymenu/mainscreens/DataSelectionMenu.cpp
speed-dreams/source-2.2.3/src/modules/userinterface/legacymenu/mainscreens/DataSelectionMenu.h
speed-dreams/source-2.2.3/src/modules/userinterface/legacymenu/mainscreens/ResearcherMenu.cpp
speed-dreams/source-2.2.3/src/modules/userinterface/legacymenu/mainscreens/ResearcherMenu.h
speed-dreams/source-2.2.3/src/modules/userinterface/legacymenu/mainscreens/mainmenu.cpp
speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/CHANGES.txt
speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backend/ConfigEnums.h
speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backend/DecisionMaker.h
speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backend/DecisionMaker.inl
speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backend/FileDataStorage.h
speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backend/FileDataStorage.inl
speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backend/Mediator.h
speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backend/Mediator.inl
speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backend/SDAConfig.cpp
speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backend/SDAConfig.h
speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backendUnitTests/ConfigTests.cpp
speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backendUnitTests/FileDataStorageTests.cpp

Also made some small refactors and relocated variable initialization from OnActivate() to MenuInit(), this way it remembers what was selected.

V22F-268 Added back-buttons

---

speed-dreams/source-2.2.3/data/data/menu/ResearcherMenu.xml
speed-dreams/source-2.2.3/src/modules/userinterface/legacymenu/mainscreens/ResearcherMenu.cpp
speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backend/ConfigEnums.h

Tested by looking at the forcefeedback checkbox in pause while racing.

V22F-306 Add working force feedback option

---

speed-dreams/source-2.2.3/src/libs/robottools/rthumandriver.cpp
speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backend/ConfigEnums.h
speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backend/DecisionMaker.inl

Recorders were enabled on main, so every session was recorded by default, which was annoying.

V22F-434 Disable recorders

---

speed-dreams/source-2.2.3/src/modules/racing/standardgame/raceinit.cpp
speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/CHANGES.txt

Some changes were missing from the CHANGES.txt

Fix changes missing from CHANGES.txt

---

speed-dreams/source-2.2.3/cmake/customthirdparty.cmake

Fixes the "can't copy file" bug when building

V22F-472 Build fails when copying fix

---

speed-dreams/source-2.2.3/cmake/thirdpartydeps.cmake
speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backendUnitTests/CMakeLists.txt

Removed the pointer manager from the code coverage as github does not want to test with shared pointers

V22F-459 Removed IPCPointerManager from code coverage

---

speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backend/BlackBoxData.cpp
speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backend/BlackBoxData.h
speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backend/DecisionMaker.h
speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backend/DecisionMaker.inl
speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backend/Mediator.h
speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backend/SocketBlackBox.h
speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backend/SocketBlackBox.inl
speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backendUnitTests/mocks/BlackBoxDataMock.h
speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backendUnitTests/mocks/DecisionMakerMock.h
speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backendUnitTests/mocks/SocketBlackBoxMock.h

Changed tickCount to unsigned long

V22F-493 Tick to ulong

---

speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backend/SQLDatabaseStorage.cpp

The database settings table will now only have items that are unique

V22F-492 Prevent duplicate settings in database

---

speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backend/DecisionMaker.h
speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backend/DecisionMaker.inl

This PR makes sure that the black box keeps performing its decision if it is slow

V22F-513 Keep decision when black box is thinking

---

speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backend/BrakeDecision.cpp
speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backend/BrakeDecision.h
speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backend/SteerDecision.cpp
speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backend/SteerDecision.h
speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backendUnitTests/DecisionsTests.cpp

Moved decision thresholds to header files. Used them as minimum values for random float

V22F-609 Random decision amount

---

.github/workflows/integration-tests.yml

This action runs with the OPTION_INTEGRATION_TESTS=ON option, so that in the future this action will run the integration tests.

V22F-615 Created action for integration tests

---

speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backend/DecisionTuple.cpp
speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backend/DecisionTuple.h
speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backend/FileDataStorage.cpp
speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backendUnitTests/FileDataStorageTests.cpp

Cover all code of the FileDataStorage files.
Additionally, update the DecisionTuple class slightly to ensure Lights and Gear are usable, though not implemented.

V22F-620 cover filedatastorage code

---

speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backend/DecisionMaker.inl
speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backend/Recorder.cpp
speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backend/Recorder.h
speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backendUnitTests/RecorderTests.cpp
speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backendUnitTests/mocks/RecorderMock.h

Implemented @suppergerrie2 requested changes

Made the test be able to run with nullptrs again

---

speed-dreams/source-2.2.3/src/modules/graphic/ssggraph/grboard.cpp
speed-dreams/source-2.2.3/src/modules/sound/snddefault/OpenalSoundInterface.cpp
speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backendUnitTests/CarControllerTests.cpp
speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backendUnitTests/DecisionsTests.cpp
speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/frontend/IndicatorConfig.cpp
speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/frontend/IndicatorConfig.h
speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/frontendUnitTests/IndicatorConfigTests.cpp

should fix code coverage failing carcontroller tests

V22F-665 Fix CarControllerTests bug

---

speed-dreams/source-2.2.3/src/modules/userinterface/textonly/textonly.cpp

V22F-765 Set the default threshold value for replay decisions

---

speed-dreams/source-2.2.3/src/modules/userinterface/legacymenu/mainscreens/DataSelectionMenu.cpp

fixed the bug for the read acces violation

V22F-772 data compression menu read acces bug

---

speed-dreams/source-2.2.3/src/modules/userinterface/legacymenu/mainscreens/ResearcherMenu.cpp

Move call to InitializeTrackLoader to before any return statements in OnActivate

V22F-805 Ensure track loader is always instantiated

---

.github/workflows/code-coverage-linux.yml
.github/workflows/test-linux.yml

This PR fixes the erorrs that occured in the the install package during the linux Actions.

V22F-919 Fix linux package install

---

speed-dreams/source-2.2.3/data/data/menu/joy2butconfigmenu.xml
speed-dreams/source-2.2.3/data/data/menu/joystickconfigmenu.xml

added background to calibration menu

V22F-921 adding background to calibration

---

speed-dreams/source-2.2.3/src/modules/userinterface/legacymenu/mainscreens/DatabaseConnectionManager.cpp

added default values, when copying the string from the database management settings

V22F-924 Read Nullpointer

---

speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backend/SocketBlackBox.inl
speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backendUnitTests/SocketBlackBoxTests.h

Changed the async test to not depend on sleeping.

V22F-952 Fixed async test
